// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button-group': string;
  'chatGpt': string;
  'code': string;
  'container': string;
  'github': string;
  'link': string;
  'message': string;
  'meta': string;
  'so': string;
  'so-post': string;
  'stackOverflow': string;
  'title': string;
  'vsCode': string;
}
export const cssExports: CssExports;
export default cssExports;
