// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'center': string;
  'cursor-default': string;
  'cursor-pointer': string;
  'flat-button': string;
  'flex': string;
  'flex-col': string;
  'flex-row': string;
  'git-information': string;
  'inactive': string;
  'm2': string;
  'm4px': string;
  'ml4': string;
  'p2': string;
  'simulate-link': string;
}
export const cssExports: CssExports;
export default cssExports;
