// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'center': string;
  'flat-button': string;
  'flex': string;
  'flex-row': string;
  'git-information': string;
  'm2': string;
  'm4px': string;
  'simulate-link': string;
}
export const cssExports: CssExports;
export default cssExports;
